//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company_Registration
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyApprovalLog
    {
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public long ApprovedBy { get; set; }
        public string Action { get; set; }
        public string Remarks { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual RegisteredCompany RegisteredCompany { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
