//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company_Registration
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyStakeholder
    {
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public string FullName { get; set; }
        public string StakeholderRole { get; set; }
        public decimal SharePercentage { get; set; }
        public string Nationality { get; set; }
        public string IdentityNumber { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual RegisteredCompany RegisteredCompany { get; set; }
    }
}
