//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company_Registration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyRegistrationDBEntities : DbContext
    {
        public CompanyRegistrationDBEntities()
            : base("name=CompanyRegistrationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyApplicant> CompanyApplicants { get; set; }
        public virtual DbSet<CompanyApprovalLog> CompanyApprovalLogs { get; set; }
        public virtual DbSet<CompanyConstitution> CompanyConstitutions { get; set; }
        public virtual DbSet<CompanyShareCapital> CompanyShareCapitals { get; set; }
        public virtual DbSet<CompanyShareholder> CompanyShareholders { get; set; }
        public virtual DbSet<CompanyStakeholder> CompanyStakeholders { get; set; }
        public virtual DbSet<RegisteredCompany> RegisteredCompanies { get; set; }
        public virtual DbSet<RegistrationPayment> RegistrationPayments { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<UltimateHoldingCompany> UltimateHoldingCompanies { get; set; }
    }
}
