//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company_Registration
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisteredCompany()
        {
            this.CompanyApprovalLogs = new HashSet<CompanyApprovalLog>();
            this.CompanyConstitutions = new HashSet<CompanyConstitution>();
            this.CompanyShareCapitals = new HashSet<CompanyShareCapital>();
            this.CompanyShareholders = new HashSet<CompanyShareholder>();
            this.CompanyStakeholders = new HashSet<CompanyStakeholder>();
            this.RegistrationPayments = new HashSet<RegistrationPayment>();
            this.UltimateHoldingCompanies = new HashSet<UltimateHoldingCompany>();
        }
    
        public long Id { get; set; }
        public string CompanyName { get; set; }
        public string RegistrationNumber { get; set; }
        public string CompanyType { get; set; }
        public string BusinessActivity { get; set; }
        public string RegisteredAddress { get; set; }
        public string RegistrationStatus { get; set; }
        public long ApplicantId { get; set; }
        public System.DateTime IncorporationDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual CompanyApplicant CompanyApplicant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyApprovalLog> CompanyApprovalLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyConstitution> CompanyConstitutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyShareCapital> CompanyShareCapitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyShareholder> CompanyShareholders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyStakeholder> CompanyStakeholders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationPayment> RegistrationPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UltimateHoldingCompany> UltimateHoldingCompanies { get; set; }
    }
}
