//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company_Registration
{
    using System;
    using System.Collections.Generic;
    
    public partial class UltimateHoldingCompany
    {
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public string UHCName { get; set; }
        public string RegistrationNumber { get; set; }
        public string CountryOfIncorporation { get; set; }
        public decimal OwnershipPercentage { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual RegisteredCompany RegisteredCompany { get; set; }
    }
}
